framework:
    messenger:
        failure_transport: async
        transports:
            async:
                dsn: '%env(RABBITMQ_URL)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

