services:
  database:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'spendless'
      MYSQL_USER: 'spendless'
      MYSQL_PASSWORD: 'supersecret'
    ports:
      - '3306:3306'
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
